# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloworld_pb2 as helloworld__pb2


class MusicServStub(object):
  """interface de serviço

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getListMusics = channel.unary_stream(
        '/MusicServ/getListMusics',
        request_serializer=helloworld__pb2.ListRequest.SerializeToString,
        response_deserializer=helloworld__pb2.Music.FromString,
        )
    self.addMusic = channel.unary_unary(
        '/MusicServ/addMusic',
        request_serializer=helloworld__pb2.Music.SerializeToString,
        response_deserializer=helloworld__pb2.BooleanReply.FromString,
        )
    self.deleteMusic = channel.unary_unary(
        '/MusicServ/deleteMusic',
        request_serializer=helloworld__pb2.MusicId.SerializeToString,
        response_deserializer=helloworld__pb2.BooleanReply.FromString,
        )


class MusicServServicer(object):
  """interface de serviço

  """

  def getListMusics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addMusic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteMusic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MusicServServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getListMusics': grpc.unary_stream_rpc_method_handler(
          servicer.getListMusics,
          request_deserializer=helloworld__pb2.ListRequest.FromString,
          response_serializer=helloworld__pb2.Music.SerializeToString,
      ),
      'addMusic': grpc.unary_unary_rpc_method_handler(
          servicer.addMusic,
          request_deserializer=helloworld__pb2.Music.FromString,
          response_serializer=helloworld__pb2.BooleanReply.SerializeToString,
      ),
      'deleteMusic': grpc.unary_unary_rpc_method_handler(
          servicer.deleteMusic,
          request_deserializer=helloworld__pb2.MusicId.FromString,
          response_serializer=helloworld__pb2.BooleanReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MusicServ', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
